name: Validate Pull Request

on: [pull_request]

jobs:
  check-prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Prettier
        run: npm install --save-dev prettier

      - name: Run Prettier
        run: |
          npx prettier --write usercss/
          npx prettier --write userscripts/

      - name: Check for changes
        run: |
          git diff --exit-code

  check-make:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Make
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Run Make Readme
        run: make readme

      - name: Check for changes
        run: |
          git diff --exit-code
